### ISSUE TITLE
Add eslint configurations

### ISSUE THREAD

**Issue by krisharma** [sandboxnu/a-eye#96]
Jake feel free to go about this as you mentioned during GM on 1/31

**Comment by jakeisnt** [comment]
Should I add a CI action for linting? Easy with [this](https://github.com/Borales/actions-yarn)

**Comment by jakeisnt** [comment]
End of the day notes:
After generating a convolution on the first module, we receive the error:
IndexSizeError: Index or size is negative or greater than the allowed amount
getPixels
src/modules/computerVision/common/filter.tsx:6

  3 | 
  4 | function getPixels(canvas: HTMLCanvasElement) {
  5 |   const ctx = canvas.getContext('2d');
> 6 |   return ctx && ctx.getImageData(0, 0, canvas.width, canvas.height);
  7 | }
  8 | 
  9 | /**
The canvas is never null, but it's likely incorrectly targeting some HTML. What's left to do - trace the path of the canvas through the application to see how it's fetched; determine what is wrong with the currently used canvas.

The second module crashes upon loading with a Chartjs issue:
TypeError: tickValue.toFixed is not a function.

Based on the stack trace, this appears to happen when one of the charts is instantiated; the chart's parameters are in some way not properly instantiated. I think this is a good opportunity to refactor kmeansStepExample and the other kmeans demo regardless - the generators seem to be inefficient when processing lots of data, as the eslint configuration continues to warn. 
A more complete refactor should really help clarify the location of the issue here, too.

**Comment by jakeisnt** [comment]
second module issue resolved

**Comment by jakeisnt** [comment]
all fixed, ready for review
